### PR TITLE
2.11.0

### PR DESCRIPTION
**Pull request by tonymorris**
New lens values, bump version, add Tony as maintainer

### CODE REVIEW

**Comment by roconnor** [comment]
- unzipL l should be defined more like: unzipL l = (l . fstL, l . sndL)  and similarly for unzipPL.
- lookupBy should probably take a predicate rather than a binary relation and a constant.
- I believe that findL does not satisfy the lens laws.

**Comment by roconnor** [comment]
I added some comments.

On Mon, 14 May 2012, tonymorris wrote:

> New lens values, bump version, add Tony as maintainer
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/tonymorris/data-lens 2.11.0
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/roconnor/data-lens/pull/6
> 
> -- Commit Summary --
> - Add Tony as maintainer
> - dot ghci for new modules
> - emptyPL
> - unzip on lens
> - notNullPL
> - bump version
> - list lenses
> 
> -- File Changes --
> 
> M .ghci (2)
> M data-lens.cabal (4)
> M src/Data/Lens/Common.hs (7)
> M src/Data/Lens/Partial/Common.hs (32)
> 
> -- Patch Links --
> 
>  https://github.com/roconnor/data-lens/pull/6.patch
>  https://github.com/roconnor/data-lens/pull/6.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/roconnor/data-lens/pull/6

## 

Russell O'Connor                                      http://r6.ca/
`All talk about `theft,''' the general counsel of the American Graphophone
Company wrote,`is the merest claptrap, for there exists no property in
ideas musical, literary or artistic, except as defined by statute.''

**Comment by tonymorris** [comment]
On May 15, 2012 4:08 PM, "roconnor" <
reply@reply.github.com>
wrote:

> - unzipL l should be defined more like: unzipL l = (l . fstL, l . sndL)
>   and similarly for unzipPL.

Ok

> - lookupBy should probably take a predicate rather than a binary relation
>   and a constant.

Agreed. I started there and went back.

> - I believe that findL does not satisfy the lens laws.

I'm a bit embarrassed that I didn't notice this myself. I got a bit too
excited after lookup.

**Comment by roconnor** [comment]
On Tue, 15 May 2012, tonymorris wrote:

> On May 15, 2012 4:08 PM, "roconnor" <
> reply@reply.github.com>
> wrote:
> 
> > - unzipL l should be defined more like: unzipL l = (l . fstL, l . sndL)
> >   and similarly for unzipPL.
> 
> Ok
> 
> > - lookupBy should probably take a predicate rather than a binary relation
> >   and a constant.
> 
> Agreed. I started there and went back.

One thing I don't like about lookupBy is that it only adjusts the first 
occurance of the key; which might catch the users by surprise ... I do 
acknowledge that the same problem exists for the Prelude lookup; however 
I'm disinclined to exacerbate the problem.

What I'd rather do is provide lookupBy and lookup for multilens which will 
be able to pick out _all_ occurances of the key.  Then there are two 
natural maps from multiLens a b to paritalLens a b called firstOccPL and 
lastOccPL which create a partial lens to the first and last occurances of 
the list of references in a multilens.

This will allow the user to construct lookup and lookupBy as you have 
defined, but the user will make required to make a conscious and explict 
choice that they want the first or last occurance.  More importantly the 
user will be required to consider the possibility that there could be more 
than one occurance, a fact that is hidden by your current proposal (and 
hidden by the existing lookup in the Prelude).

## 

Russell O'Connor                                      http://r6.ca/
`All talk about `theft,''' the general counsel of the American Graphophone
Company wrote,`is the merest claptrap, for there exists no property in
ideas musical, literary or artistic, except as defined by statute.''

**Comment by tonymorris** [comment]
I have pushed fix for:
- unzipL l should be defined more like: unzipL l = (l . fstL, l . sndL) and similarly for unzipPL.
  Written using applicative syntax
- lookupBy should probably take a predicate rather than a binary relation and a constant.
  It now does, though lookup takes Eq constraint and a constant
- I believe that findL does not satisfy the lens laws.
  Has been deleted.

I have left lookup\* in lieu the previous comment. I agree with the sentiment of lookup\* altering only one of the keys. Is data-lens ready for reinstatement of MultiLens? If not, what shall we do in the meantime?

**Comment by roconnor** [comment]
I've pushed lookupBy as a multilens in the master branch.

I'm starting to reconsider the partial lens lookupBy since it would be 
more efficent than frontPL . lookupByL.

## 

Russell O'Connor                                      http://r6.ca/
`All talk about `theft,''' the general counsel of the American Graphophone
Company wrote,`is the merest claptrap, for there exists no property in
ideas musical, literary or artistic, except as defined by statute.''

**Comment by roconnor** [comment]
Now addressed by https://github.com/roconnor/data-lens/commit/d91d5dce9142b728f725cfefa70da10ea7a76778

**Pull request closed without merging**
